port: 8080
mysql:
  host: 127.0.0.1
  port: 3306
  username: root
  password: root
redis:
  host: 127.0.0.1
  port: 6379
  db: 0
  password:
elasticSearch:
  host: http://127.0.0.1
  port: 9200
aliOss:
  accessId: xxx
  accessKey: xxx
  host: https://xxx.oss-cn-hangzhou.aliyuncs.com
  dir: /user-dirs
  bucket: xxx